#!/bin/bash

export SYSREPO=/home/ryan/sysrepo

usage() {
	local -r COMMAND=${BASH_SOURCE[0]##*/}
	cat <<- _EOF_
		Usage: ${COMMAND} [COMMAND] [OPTIONS]

		Unified command-line frontend for devtools.

		COMMANDS
            clone   Used to clone a package

		OPTIONS
		    -h, --help     Show this help text
_EOF_
}

if (( $# < 1 )); then
	usage
	exit 1
fi

while (( $# )); do
	case $1 in
		-h|--help)
			usage
			exit 0
			;;
		clone)
            git clone git@github.com:RyanBruno/sysarch.git
			exit 0
			;;
		build)
            makepkg
			exit 0
			;;
        release)
            cp *.pkg.tar.* ${SYSREPO} # TODO
			exit 0
			;;
        update)
            repo-add ${SYSREPO}/system.db.tar.gz ${SYSREPO}/*.pkg.tar.*
            # repo-add & sign
			exit 0
			;;
		*)
			echo "invalid command:" "$1"
			exit -1
			;;
	esac
done


